// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2zcmk5wa3F_TU75lqKrTKhixmtd8cAoQ',
    appId: '1:524076284803:web:40cd773cc505797c91d4b6',
    messagingSenderId: '524076284803',
    projectId: 'precisoapp',
    authDomain: 'precisoapp.firebaseapp.com',
    storageBucket: 'precisoapp.firebasestorage.app',
    measurementId: 'G-NX99N121J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4F98adJO-92fwpC1bHhPuRp_9XuzPBok',
    appId: '1:524076284803:android:7e68c4655ce3940791d4b6',
    messagingSenderId: '524076284803',
    projectId: 'precisoapp',
    storageBucket: 'precisoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-P5TY9h-LxC2T1oddNN9tK6h2gQ09dQs',
    appId: '1:524076284803:ios:7d9b60e258750b3891d4b6',
    messagingSenderId: '524076284803',
    projectId: 'precisoapp',
    storageBucket: 'precisoapp.firebasestorage.app',
    iosBundleId: 'com.example.preciso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-P5TY9h-LxC2T1oddNN9tK6h2gQ09dQs',
    appId: '1:524076284803:ios:7d9b60e258750b3891d4b6',
    messagingSenderId: '524076284803',
    projectId: 'precisoapp',
    storageBucket: 'precisoapp.firebasestorage.app',
    iosBundleId: 'com.example.preciso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2zcmk5wa3F_TU75lqKrTKhixmtd8cAoQ',
    appId: '1:524076284803:web:cc087a4261b650c191d4b6',
    messagingSenderId: '524076284803',
    projectId: 'precisoapp',
    authDomain: 'precisoapp.firebaseapp.com',
    storageBucket: 'precisoapp.firebasestorage.app',
    measurementId: 'G-S06DTDTC6P',
  );
}
